baseURL = "/"
languageCode = "en-us"
 
DefaultContentLanguage = "en"
copyright = "Everything is mine"

[languages]

  [languages.en]
    title = "Ambi Translate"
    weight = 1

    [languages.en.params]
      revolution="The Revolution is Here"
      otherLang = "ѸsӼmӼY*"
      otherLangLink="/ip_ni"
      signUp = "Sign up for free"
      logIn = "Log in to Ambi Translate"
      TTSCodenames = "Harbringers"
      NumLangsSpoken = "Languages Spoken"
      NumLangsSpokenFigure = "140+"
      DailyUsers = "Daily Users"
      DailyUsersFigure = "935K+"
      TotalTranslations="Total Translations Processed"
      TotalTranslationsFigure="a fair few"
      InTodaysWorld="In today's modern world, communication reigns. Technology helps us communicate anything with anyone, at any time, like never before in human history."
      Grandma="Tools such as Twitter allow us to share quick updates about our day in seconds. Facebook allows us to catch up with grandma and childhood friends without breaking a sweat."
      Yesteryear="Stumbling on language barriers is so yesteryear."
      Shakespeare="If you followed Shakespeare on Twitter, could you understand him?"
      WhatYouMean="When you travel, are you ever sure that you're saying what you mean?"
      ExoticCompliment="Wouldn't it be nice to pass off devastating insults as foreign, exotic compliments?"
      WithTranslate="With Ambi Translate, the whole world can speak clearly."
      How="How does it work?"
      JustSpeak="It's simple! Just speak."
      Naturally="Speak <span class='underline'>naturally</span>"
      InstantTranslation="Our Harbringers of the Revolution can translate for you instantly, in any one of over 140 languages."
      JustLike="Just like real translators, they do their best to match your original tone and style."
      Confidently="Speak <span class='underline'>confidently</span>"
      Database="The Harbringers have learned from a database of over <strong>sixty-five billion written documents</strong> and a further  <strong>eighty-four billion audio recordings</strong>. Not only that, but they also learn from corrections submitted by millions of people each day."
      FromAnywherely="Speak <span class='underline'>from anywhere</span>"
      TheWayYou="Ambi Translate works for you, the way you work."
      AmbiMail="Use Ambi Mail?"
      Inbox="@Daydream practically lives in his inbox."
      Here="Prefer to use Ambi Here?"
      CatchUp="Catch up with @JustCause."
      OnCall="Need to make sense of a call?"
      AmbiSpeak="Add a Harbringer to your Ambi Speak call for free!"
      YouNeedAccount="All you need is an Ambi account."
      DontHaveOne="Don't have one? Sign up for free:"
      AtAmbi="@ambi.com"
      NameOne="@Daydream"
      NameTwo="@JustCause"
      WaitingFor="So what are you waiting for?"
      
  [languages.ip_ni]
    title = "8Ѿǌރsঔǌኻ൝R Ӽ˟mȬ"
    weight = 2

    [languages.ip_ni.params]
      revolution="sӼ 8ኻ8Ѹ 8Ѹ൝R ঔYӼѾ0.ރYF82ߡM"   
      otherLang = "English"
      otherLangLink="/"
      signUp = "இ0. 88ኻ, ኻY, ঔ⅖Ӽjʈ"
      logIn = "YѾ ঔӼ 8Ѿǌރsঔǌኻ൝R ⅖Ygل Ӽ˟mȬ"
      TTSCodenames = "sኻ8⅖ঔӼኻ˟ኻǌ<e"
      NumLangsSpoken = "ঔ8XYஇs s8⅖ǌ0.⅖ঔǌgل"
      NumLangsSpokenFigure = "+04Tߴ"
      DailyUsers = "sኻ8s٤fڬ *ރӼǌ}Ќ"
      DailyUsersFigure = "+.+{{3Ɛ"
      TotalTranslations="sঔYӼѾǌރsঔǌኻ൝R ރǌѾY൝R Yjʈ ኻǌyY"
      TotalTranslationsFigure="8mYs ,8XӼރ"
      InTodaysWorld=",dރኻYg ѸѾӼg s0. s'*ǌdYѾ ,8mӼѾ .sঔ⅖Ӽ8ኻ ኻ8F8ঔ ঔኻ8dYm 8XӼރ ঔӼ ঔǌm0.Ѹ .*ኻYѾsӼѸ sஇރ8Ѹ ঔYӼѾǌΔӼঔ0.mmYΔ 8ѾǌΔӼঔ0.mmYΔ 8ኻY,8˟ Ѿǌ ⅖ঔӼѸѾ*ঔǌ ,8ঔY*ঔǌ *ঔǌ *⅖YރYঔѸΔ8൝R ঔw&"
      Grandma="Ѿ0.YѸѾӼg ѸѾӼg s0. s0. s8Ѿǌdஇ0. இ0. YѾ YѾ .Ѿǌ8gs ѸΔ0.s 8ኻǌѸs .sdঔYΔ8s XΔӼ0.ᆹ ኻ0.Y ঔӼ ǌmdঔǌኻ⅖ sdঔ8Ӽኻ, *ǌd dYYѸdރӼѸΔ ѸΔѾǌΔ ⅖ঔӼXǌ8ኻ˟ sǌ dঔǌ sgYރރǌ gYރރǌ Ѿ0.Y˟ǌ ǌ ኻ8ѾѾӼg൝R sރYY൝R XYY˟8ΔǌyY"
      Yesteryear=".ኻǌ8*ኻ8Ѿs8* Ys ঔY 8⅖ǌ0.⅖ঔǌރ sӼ sኻ8Ӽኻኻǌ˟ ⅖ঔӼރ˟m0.Ѿjʈ"
      Shakespeare="0.Y* dঔǌѾsኻ8dঔ0. ঔY ?mӼѸ d8gYރރY, dރ0.YΔ ,ኻ8ѾѾӼg൝R 8ኻǌ8இs8XǌѸjʈ ,w&"
      WhatYouMean="8ኻ' 0.Y* ѾǌѸg ,ރ8FǌኻѾ ѾǌѸѾ 8ኻ0.s ⅖ঔӼ*ǌs ?ঔǌ8m ኻ8F8 8ኻǌ ঔ8Ѹǅb"
      ExoticCompliment="YѾ ssǌஇ ,,Y 8ΔӼঔ ѾӼ sѾރ0.sঔӼ ,ঔ⅖Ӽ8ኻY, ΔӼѾY78 ⅖ঔӼѾǌѾsǌF8d ?sѾঔ8mӼރஇmYΔ 8˟ sǌ Ѿ'ঔdރ0.Yǅb"
      WithTranslate="dރኻYg 8ރYѸg 8ѸѾ Xǌ8இs .*ރኻǌ8ރΔ ঔǌΔ ѸѾӼǅb ,8Ѿǌރsঔǌኻ൝R Ӽ˟mȬ"
      How="?XኻYg ѾӼ s8Yd gY<e"
      JustSpeak=".Xǌ8இs !8ރஇmӼs Ѿs0.|r s'Ѿw&"
      Naturally="<span class='underline'>*ރރǌኻ0.Ѿǌঔ</span> Xǌ8இjʈ"
      InstantTranslation="0.Y* 8ѾǌރsঔǌኻѾ 8ѸѾ ኻ8FY 8ঔY ,Y ,Y .s8⅖ǌ0.⅖ঔǌރ ,*ރѾঔǌѾsঔӼ ঔӼ ኻY, ঔǌΔ *ঔǌ ঔYӼѾ0.ރYF82ߡM ኻ0.Ոx sኻ8⅖ঔӼኻ˟ኻǌ<e 04Tߴ"
      JustLike="ኻ0.Y* ,sኻYѾǌރsঔǌኻѾ 8ঔYѾ YѾ *8ѸѾ ኻӼ8ѸѾ .8ރ*Ѿs ރǌ8ኻ ރǌঔӼ⅖ӼኻY ѸΔѾǌm 8XӼރ Yd Ѿs8˟ dঔǌ Ѿs0.|r"
      Confidently="<span class='underline'>*ރރǌѾঔ8dӼ,ঔYΔ </span> Xǌ8இjʈ"
      Database="<strong>ঔ8ѾѾӼኻg</strong> *8ѸѾ ,ѾǌѸѾ d8ѾѾӼm˟0.s <strong>8FӼ,-*Ѿ7Ӽs</strong> .<strong>s⅖ঔӼdኻYΔ8ኻ</strong> 8ރஇY8இ ኻ8FY *ރঔY ,Y ,Y sঔYӼރރӼm d8ঔኻǌ8ރ ঔኻǌ8ރ 8FǌѸ ኻ8ѸѾኻ0., mYኻ, mYኻ, <strong>ኻ0.Y,-*ѾѸ⅖Ӽ8</strong> ѸΔǌ8 <strong>sѾঔ8m0.ΔYd</strong> .*ǌd 8sǌ˟ǌѾǌd sঔYӼѾΔ8ኻኻYΔ *˟ Ѿ0.˟ <strong>ঔYӼރރӼ˟</strong> <strong>ঔYӼރރӼ˟</strong> <strong>YӼd0.ǌ</strong> dঔǌ Ysރǌ ǌ ǌ 8Ѹ൝R ѾYY* sኻ8⅖ঔӼኻ˟ኻǌ<e"
      FromAnywherely="<span class='underline'>mYኻ, 8ኻ8Ѹg*ঔǌ</span> Xǌ8இjʈ"
      TheWayYou=",0.Y* sXኻYg .XኻYg *ǌg 8ѸѾ ኻY, 8Ѿǌރsঔǌኻ൝R Ӽ˟mȬ"
      AmbiMail="8s٤fڬ ?ރӼǌủؿ Ӽ˟mȬ"
      Inbox="*ރރǌΔӼѾΔǌኻஇ s8FӼރ .7Y˟ঔӼ ঔӼ sӼѸ mǌ8ኻd*ǌ}Ќ@"
      Here="8s0. YѾ ኻ8,8ኻ9.]ǹ ?8ኻ8<e Ӽ˟mȬ"
      CatchUp="ѸѾӼg இ0. ѸΔѾǌ- .8s0.ǌ-Ѿs0.|r@"
      OnCall="YѾ 8sঔ8s ,Y 8Xǌm ?ރރǌΔ ǌ d88Y*"
      AmbiSpeak="ኻ0.Y* YѾ !88ኻ, ኻY, ރރǌΔ ǌ Xǌ8இjʈ ኻ8⅖ঔӼኻ˟ኻǌ<e Ӽ˟mȬ ddȬ"
      YouNeedAccount="0.Y* d88ঔ sӼ ঔǌ .Ѿঔ0.YΔΔǌ Ӽ˟mȬ ރރȬ"
      DontHaveOne="இ0. ?8ঔY 8FǌѸ :88ኻ, ኻY, ঔ⅖Ӽjʈ Ѿ'ঔY}Ќ"
      AtAmbi="mYΔ.Ӽ˟mǌ@"
      NameOne="mǌ8ኻd*ǌ}Ќ@"
      NameTwo="8s0.ǌ-Ѿs0.|r@"
      WaitingFor="0.Y* ѾǌѸg ⅖ঔӼѾӼǌg ?ኻY, 8ኻǌ Yjʈ"


[params]

  [params.navigation]
    help = "Help"